spring.application.name=GoalPlanner
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security=DEBUG
cors.allowed-origins=http://localhost:5173,http://localhost:5174
jwt.expiration=86400000
server.port=8081


spring.datasource.url=your_database
spring.datasource.username=your_postgres_user
spring.datasource.password=password
jwt.secret=your-secret-code-for-generate-jwt

#cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#cors.allowed-headers=*
#cors.allow-credentials=true
#cors.max-age=3600
#cors.mapping-path=/api/**


